name: Development Build

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/nightly-build.ccs'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List nightly-build.ccs
        run: ls -l .github/workflows/nightly-build.ccs

      - name: Upload nightly-build.ccs
        uses: actions/upload-artifact@v4
        with:
          name: Nightly-Build
          path: .github/workflows/nightly-build.ccs
